### ISSUE TITLE
Files are strange - Generate Icons & Splash (Launch) Images

### ISSUE THREAD

**Issue by findvivian** [FokkeZB/TiCons-Server#1]
Hi Fokke,

Noticed you have updated the Generator again and took a test run. Currently it seems like it just takes the 2208x2208 splash image and sizes it down without cropping. GooglePlay image is also not cropped and sized like they used to be. Is there a quick fix for this?

Is it possible to upload your previous version to another link for use? It works really stable and has all the nice features since being able to customize the ios versus android icon is also a nice feature.

Thank you!

**Comment by findvivian** [comment]
![image](https://cloud.githubusercontent.com/assets/12780933/9258428/8ec74cde-41c9-11e5-9f8f-cc35a63f2bf3.png)

![image](https://cloud.githubusercontent.com/assets/12780933/9258472/c5e77b9e-41c9-11e5-8b0f-cbffa6001f7d.png)

![image](https://cloud.githubusercontent.com/assets/12780933/9258530/00b757d0-41ca-11e5-9503-ee114a246572.png)

![image](https://cloud.githubusercontent.com/assets/12780933/9258544/186bc9d8-41ca-11e5-9504-634851ed23e4.png)

**Comment by FokkeZB** [comment]
Please try again. I've updated the CLI version it depended on.

**Comment by findvivian** [comment]
Same thing happens :)

**Comment by findvivian** [comment]
Would you happen to have the old version uploaded to another link? 
It was perfect!

**Comment by FokkeZB** [comment]
No, I don't keep the old version around. Could you attach the input you used to get these results as I can't reproduce? Also, the filenames you show in the screenshots are not those the current version should get you.

**Comment by findvivian** [comment]
<img width="759" alt="screen shot 2015-08-14 at 10 35 31 am" src="https://cloud.githubusercontent.com/assets/12780933/9276230/981052fc-4270-11e5-9c8c-066ec073960e.png">
<img width="674" alt="screen shot 2015-08-14 at 10 37 09 am" src="https://cloud.githubusercontent.com/assets/12780933/9276228/980ed8fa-4270-11e5-8e59-8ee3c01631b6.png">
<img width="807" alt="screen shot 2015-08-14 at 10 37 37 am" src="https://cloud.githubusercontent.com/assets/12780933/9276229/980f8c0a-4270-11e5-8bdf-125d90c3ee77.png">

**Comment by findvivian** [comment]
I just ran it again and the same results. :/

**Comment by FokkeZB** [comment]
Could you attach your input file?

**Comment by findvivian** [comment]
![splash](https://cloud.githubusercontent.com/assets/12780933/9308691/76f326b6-44d3-11e5-9903-ff89664fe6c7.png)

**Comment by FokkeZB** [comment]
Thank you:

* Icons have never been cropped if the input is already square.
* Your input does not have a transparent area. I tested with one that does and it worked fine.
* I will push a new version that will crop the marketplace feature unless you have disabled cropping.
