### ISSUE TITLE
Zip is not working

### ISSUE THREAD

**Issue by FokkeZB** [FokkeZB/TiCons-Server#4]
After publishing a new version zip is no longer working:

```
Error: Command failed: /bin/sh -c zip -r /opt/app_source/web/public/download/42695030-6b72-11e5-9821-db99116d50ec.zip ./
```

**Comment by adamh04** [comment]
I am also receiving this same error.

**Comment by FokkeZB** [comment]
Might have to switch to `tar.gz`.

**Comment by FokkeZB** [comment]
Fixed: https://jira.appcelerator.org/browse/NODEJS-2303

**Comment by adamh04** [comment]
Seems to be working great now, thank you!

Adam Hayworth
TPI
Application Development
Variable Data Print | Direct Mail
Las Vegas • Des Moines • New Orleans
D 515.241.4507 • C 515.473.1387

On Oct 7, 2015, at 4:02 AM, Fokke Zandbergen <notifications@github.com<mailto:notifications@github.com>> wrote:


Fixed: https://jira.appcelerator.org/browse/NODEJS-2303
